// <auto-generated />
using System;
using HattmakarenWebbAppGrupp03.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HattmakarenWebbAppGrupp03.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413092700_AddHat")]
    partial class AddHat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HatMaterial", b =>
                {
                    b.Property<int>("HatsHId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialsMId")
                        .HasColumnType("int");

                    b.HasKey("HatsHId", "MaterialsMId");

                    b.HasIndex("MaterialsMId");

                    b.ToTable("HatMaterial");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.AssignedOrders", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<int>("OId")
                        .HasColumnType("int");

                    b.Property<int>("OrderOId")
                        .HasColumnType("int");

                    b.HasKey("EId");

                    b.HasIndex("EmployeeEId");

                    b.HasIndex("OrderOId");

                    b.ToTable("AssignedOrders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Customer", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.CustomerManager", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerCId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeEId")
                        .HasColumnType("int");

                    b.HasKey("EId");

                    b.HasIndex("CustomerCId");

                    b.HasIndex("EmployeeEId");

                    b.ToTable("CustomerManagers");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Employee", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("accesslevel")
                        .HasColumnType("int");

                    b.HasKey("EId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Hat", b =>
                {
                    b.Property<int>("HId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HId"));

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderOId")
                        .HasColumnType("int");

                    b.Property<string>("PicturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StandardHat")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HId");

                    b.HasIndex("EmployeeEId");

                    b.HasIndex("OrderOId");

                    b.ToTable("Hats");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Material", b =>
                {
                    b.Property<int>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MeasuringUnits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.MaterialOrder", b =>
                {
                    b.Property<int>("MoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoId"));

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<bool>("Printed")
                        .HasColumnType("bit");

                    b.HasKey("MoId");

                    b.HasIndex("EmployeeEId");

                    b.ToTable("MaterialOrders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Order", b =>
                {
                    b.Property<int>("OId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<bool>("Express")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PrelDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeEId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MaterialMaterialOrder", b =>
                {
                    b.Property<int>("MaterialOrdersMoId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialsMId")
                        .HasColumnType("int");

                    b.HasKey("MaterialOrdersMoId", "MaterialsMId");

                    b.HasIndex("MaterialsMId");

                    b.ToTable("MaterialMaterialOrder");
                });

            modelBuilder.Entity("HatMaterial", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Hat", null)
                        .WithMany()
                        .HasForeignKey("HatsHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.AssignedOrders", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Order", "Order")
                        .WithMany("AssignedEmployees")
                        .HasForeignKey("OrderOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.CustomerManager", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Customer", "Customer")
                        .WithMany("Managed")
                        .HasForeignKey("CustomerCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Hat", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", null)
                        .WithMany("CreatedHats")
                        .HasForeignKey("EmployeeEId");

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Order", null)
                        .WithMany("Hats")
                        .HasForeignKey("OrderOId");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.MaterialOrder", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", null)
                        .WithMany("CreatedMaterialOrders")
                        .HasForeignKey("EmployeeEId");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Order", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", null)
                        .WithMany("HandledOrders")
                        .HasForeignKey("EmployeeEId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MaterialMaterialOrder", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.MaterialOrder", null)
                        .WithMany()
                        .HasForeignKey("MaterialOrdersMoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Customer", b =>
                {
                    b.Navigation("Managed");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Employee", b =>
                {
                    b.Navigation("CreatedHats");

                    b.Navigation("CreatedMaterialOrders");

                    b.Navigation("HandledOrders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Order", b =>
                {
                    b.Navigation("AssignedEmployees");

                    b.Navigation("Hats");
                });
#pragma warning restore 612, 618
        }
    }
}
