// <auto-generated />
using System;
using HattmakarenWebbAppGrupp03.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HattmakarenWebbAppGrupp03.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417152330_AddDateToHatOrder")]
    partial class AddDateToHatOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.CustomActivity", b =>
                {
                    b.Property<int>("AId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AId");

                    b.HasIndex("EId");

                    b.ToTable("CustomActivities");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Customer", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.CustomerManager", b =>
                {
                    b.Property<int>("EId")
                        .HasColumnType("int");

                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EId", "CId");

                    b.HasIndex("CId");

                    b.ToTable("CustomerManagers");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Employee", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("accesslevel")
                        .HasColumnType("int");

                    b.HasKey("EId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Hat", b =>
                {
                    b.Property<int>("HId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StandardHat")
                        .HasColumnType("bit");

                    b.HasKey("HId");

                    b.HasIndex("EmployeeEId");

                    b.ToTable("Hats");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.HatMaterial", b =>
                {
                    b.Property<int>("HId")
                        .HasColumnType("int");

                    b.Property<int>("MId")
                        .HasColumnType("int");

                    b.HasKey("HId", "MId");

                    b.HasIndex("MId");

                    b.ToTable("HatMaterials");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.HatOrder", b =>
                {
                    b.Property<int>("HId")
                        .HasColumnType("int");

                    b.Property<int>("OId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HId", "OId");

                    b.HasIndex("EId");

                    b.HasIndex("OId");

                    b.ToTable("HatOrders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.HatSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("HatOrderHId")
                        .HasColumnType("int");

                    b.Property<int>("HatOrderId")
                        .HasColumnType("int");

                    b.Property<int>("HatOrderOId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HatOrderHId", "HatOrderOId");

                    b.ToTable("HatSchedule");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Material", b =>
                {
                    b.Property<int>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MId"));

                    b.Property<double>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("MeasuringUnits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.MaterialOrder", b =>
                {
                    b.Property<int>("MoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoId"));

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<bool>("Printed")
                        .HasColumnType("bit");

                    b.HasKey("MoId");

                    b.HasIndex("EmployeeEId");

                    b.ToTable("MaterialOrders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Order", b =>
                {
                    b.Property<int>("OId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OId"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<bool>("Express")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PrelDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeEId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.OrderOfMaterials", b =>
                {
                    b.Property<int>("OId")
                        .HasColumnType("int");

                    b.Property<int>("MoId")
                        .HasColumnType("int");

                    b.HasKey("OId", "MoId");

                    b.HasIndex("MoId");

                    b.ToTable("OrderOfMaterials");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.CustomActivity", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", "Employee")
                        .WithMany("Activities")
                        .HasForeignKey("EId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.CustomerManager", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Customer", "Customer")
                        .WithMany("Managed")
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", "Employee")
                        .WithMany("ManagedCustomers")
                        .HasForeignKey("EId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Hat", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", null)
                        .WithMany("CreatedHats")
                        .HasForeignKey("EmployeeEId");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.HatMaterial", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Hat", "Hat")
                        .WithMany("Materials")
                        .HasForeignKey("HId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Material", "Material")
                        .WithMany("MaterialsForHats")
                        .HasForeignKey("MId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hat");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.HatOrder", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", "Employee")
                        .WithMany("AssignedHats")
                        .HasForeignKey("EId");

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Hat", "Hat")
                        .WithMany("HatInOrders")
                        .HasForeignKey("HId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Order", "Order")
                        .WithMany("HatOrders")
                        .HasForeignKey("OId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Hat");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.HatSchedule", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.HatOrder", "HatOrder")
                        .WithMany()
                        .HasForeignKey("HatOrderHId", "HatOrderOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("HatOrder");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.MaterialOrder", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", null)
                        .WithMany("CreatedMaterialOrders")
                        .HasForeignKey("EmployeeEId");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Order", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", null)
                        .WithMany("HandledOrders")
                        .HasForeignKey("EmployeeEId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.OrderOfMaterials", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.MaterialOrder", "MaterialOrder")
                        .WithMany("Orders")
                        .HasForeignKey("MoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Order", "Order")
                        .WithMany("MaterialOrders")
                        .HasForeignKey("OId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialOrder");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Customer", b =>
                {
                    b.Navigation("Managed");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Employee", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("AssignedHats");

                    b.Navigation("CreatedHats");

                    b.Navigation("CreatedMaterialOrders");

                    b.Navigation("HandledOrders");

                    b.Navigation("ManagedCustomers");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Hat", b =>
                {
                    b.Navigation("HatInOrders");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Material", b =>
                {
                    b.Navigation("MaterialsForHats");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.MaterialOrder", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Order", b =>
                {
                    b.Navigation("HatOrders");

                    b.Navigation("MaterialOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
