// <auto-generated />
using System;
using HattmakarenWebbAppGrupp03.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HattmakarenWebbAppGrupp03.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410083302_hattrelationer")]
    partial class hattrelationer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HatMaterial", b =>
                {
                    b.Property<string>("HatsHatID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialsMID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HatsHatID", "MaterialsMID");

                    b.HasIndex("MaterialsMID");

                    b.ToTable("HatMaterial");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Customer", b =>
                {
                    b.Property<string>("Cid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cid");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Employee", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNr")
                        .HasColumnType("int");

                    b.Property<int>("accesslevel")
                        .HasColumnType("int");

                    b.HasKey("EId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Hat", b =>
                {
                    b.Property<string>("HatID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PicturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StandardHat")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HatID");

                    b.HasIndex("EmployeeEId");

                    b.HasIndex("OrderId");

                    b.ToTable("Hats");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Material", b =>
                {
                    b.Property<string>("MID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MeasuringUnits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.MaterialOrder", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<bool>("Utskriven")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeEId");

                    b.ToTable("MaterialOrders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Anteckning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BeställningsDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<bool>("Express")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PreliminärtLeveransDatum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rabatt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RabattBeskrivning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeEId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MaterialMaterialOrder", b =>
                {
                    b.Property<string>("MaterialOrdersID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialsMID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaterialOrdersID", "MaterialsMID");

                    b.HasIndex("MaterialsMID");

                    b.ToTable("MaterialMaterialOrder");
                });

            modelBuilder.Entity("HatMaterial", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Hat", null)
                        .WithMany()
                        .HasForeignKey("HatsHatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Hat", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", null)
                        .WithMany("CreatedHats")
                        .HasForeignKey("EmployeeEId");

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Order", null)
                        .WithMany("Hats")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.MaterialOrder", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", null)
                        .WithMany("CreatedMaterialOrders")
                        .HasForeignKey("EmployeeEId");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Order", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Employee", null)
                        .WithMany("HandledOrders")
                        .HasForeignKey("EmployeeEId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MaterialMaterialOrder", b =>
                {
                    b.HasOne("HattmakarenWebbAppGrupp03.Models.MaterialOrder", null)
                        .WithMany()
                        .HasForeignKey("MaterialOrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattmakarenWebbAppGrupp03.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Employee", b =>
                {
                    b.Navigation("CreatedHats");

                    b.Navigation("CreatedMaterialOrders");

                    b.Navigation("HandledOrders");
                });

            modelBuilder.Entity("HattmakarenWebbAppGrupp03.Models.Order", b =>
                {
                    b.Navigation("Hats");
                });
#pragma warning restore 612, 618
        }
    }
}
